DROP DATABASE IF EXISTS dataset_b_dw;
CREATE DATABASE dataset_b_dw;
USE dataset_b_dw;
CREATE TABLE dim_time (
TIME_ID DATETIME,
YEAR_ID INT,
MONTH_ID INT,
PRIMARY KEY (TIME_ID)
);
CREATE TABLE dim_location (
LOCATION_ID INT,
PARISH VARCHAR(255),
MUNICIPALITY VARCHAR(255),
DISTRICT VARCHAR(255),
PRIMARY KEY (LOCATION_ID)
);
CREATE TABLE dim_voltage (
VOLTAGE_ID INT,
VOLTAGE_LEVEL VARCHAR(255),
PRIMARY KEY (VOLTAGE_ID)
);
CREATE TABLE fact_consumption (
TIME_ID DATETIME,
LOCATION_ID INT,
VOLTAGE_ID INT,
ENERGY_CONSUMPTION DOUBLE,
PRIMARY KEY (TIME_ID, LOCATION_ID, VOLTAGE_ID),
FOREIGN KEY (TIME_ID) REFERENCES dim_time (TIME_ID),
FOREIGN KEY (LOCATION_ID) REFERENCES dim_location (LOCATION_ID),
FOREIGN KEY (VOLTAGE_ID) REFERENCES dim_voltage (VOLTAGE_ID)
);
